package com.nearme.moin.nearme;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by moin on 2/27/15.
 */
public class Countries {

    public Map<String, String> countries;
    public Map<String, String> extensions;

    public Countries() {

        countries = new HashMap<>();

        countries.put("Afghanistan", 	"AF");
        countries.put("Albania", 	"AL");
        countries.put("Algeria", 	"DZ");
        countries.put("American Samoa", 	"AS");
        countries.put("Andorra", 	"AD");
        countries.put("Angola", 	"AO");
        countries.put("Anguilla", 	"AI");
        countries.put("Antarctica", 	"AQ");
        countries.put("Antigua And Barbuda", 	"AG");
        countries.put("Argentina", 	"AR");
        countries.put("Armenia", 	"AM");
        countries.put("Aruba", 	"AW");
        countries.put("Australia", 	"AU");
        countries.put("Austria", 	"AT");
        countries.put("Azerbaijan", 	"AZ");
        countries.put("Bahamas", 	"BS");
        countries.put("Bahrain", 	"BH");
        countries.put("Bangladesh", 	"BD");
        countries.put("Barbados", 	"BB");
        countries.put("Belarus", 	"BY");
        countries.put("Belgium", 	"BE");
        countries.put("Belize", 	"BZ");
        countries.put("Benin", 	"BJ");
        countries.put("Bermuda", 	"BM");
        countries.put("Bhutan", 	"BT");
        countries.put("Bolivia", 	"BO");
        countries.put("Bosnia And Herzegovina", 	"BA");
        countries.put("Botswana", 	"BW");
        countries.put("Brazil", 	"BR");
        countries.put("Brunei Darussalam", 	"BN");
        countries.put("Bulgaria", 	"BG");
        countries.put("Burkina Faso", 	"BF");
        countries.put("Burundi", 	"BI");
        countries.put("Cambodia", 	"KH");
        countries.put("Cameroon", 	"CM");
        countries.put("Canada", 	"CA");
        countries.put("Cape Verde", 	"CV");
        countries.put("Cayman Islands", 	"KY");
        countries.put("Central African Republic", 	"CF");
        countries.put("Chad", 	"TD");
        countries.put("Chile", 	"CL");
        countries.put("China", 	"CN");
        countries.put("Christmas Island", 	"CX");
        countries.put("Cocos (Keeling) Islands", 	"CC");
        countries.put("Colombia", 	"CO");
        countries.put("Comoros", 	"KM");
        countries.put("Cook Islands", 	"CK");
        countries.put("Costa Rica", 	"CR");
        countries.put("Croatia", 	"HR");
        countries.put("Cuba", 	"CU");
        countries.put("Cyprus", 	"CY");
        countries.put("Czech Republic", 	"CZ");
        countries.put("Denmark", 	"DK");
        countries.put("Djibouti", 	"DJ");
        countries.put("Dominica", 	"DM");
        countries.put("Dominican Republic", 	"DO");
        countries.put("Ecuador", 	"EC");
        countries.put("Egypt", 	"EG");
        countries.put("El Salvador", 	"SV");
        countries.put("Equatorial Guinea", 	"GQ");
        countries.put("Eritrea", 	"ER");
        countries.put("Estonia", 	"EE");
        countries.put("Ethiopia", 	"ET");
        countries.put("Falkland Islands (Malvinas)", 	"FK");
        countries.put("Faroe Islands", 	"FO");
        countries.put("Fiji", 	"FJ");
        countries.put("Finland", 	"FI");
        countries.put("France", 	"FR");
        countries.put("French Polynesia", 	"PF");
        countries.put("Gabon", 	"GA");
        countries.put("Gambia", 	"GM");
        countries.put("Georgia", 	"GE");
        countries.put("Germany", 	"DE");
        countries.put("Ghana", 	"GH");
        countries.put("Gibraltar", 	"GI");
        countries.put("Greece", 	"GR");
        countries.put("Greenland", 	"GL");
        countries.put("Grenada", 	"GD");
        countries.put("Guam", 	"GU");
        countries.put("Guatemala", 	"GT");
        countries.put("Guinea", 	"GN");
        countries.put("Guinea-Bissau", 	"GW");
        countries.put("Guyana", 	"GY");
        countries.put("Haiti", 	"HT");
        countries.put("Holy See (Vatican City State)", 	"VA");
        countries.put("Honduras", 	"HN");
        countries.put("Hong Kong", 	"HK");
        countries.put("Hungary", 	"HU");
        countries.put("Iceland", 	"IS");
        countries.put("India", 	"IN");
        countries.put("Indonesia", 	"ID");
        countries.put("Iran) Islamic Republic Of", 	"IR");
        countries.put("Iraq", 	"IQ");
        countries.put("Ireland", 	"IE");
        countries.put("Isle Of Man", 	"IM");
        countries.put("Israel", 	"IL");
        countries.put("Italy", 	"IT");
        countries.put("Jamaica", 	"JM");
        countries.put("Japan", 	"JP");
        countries.put("Jordan", 	"JO");
        countries.put("Kazakhstan", 	"KZ");
        countries.put("Kenya", 	"KE");
        countries.put("Kiribati", 	"KI");
        countries.put("South Korea", 	"KR");
        countries.put("Kuwait", 	"KW");
        countries.put("Kyrgyzstan", 	"KG");
        countries.put("Laos", 	"LA");
        countries.put("Latvia", 	"LV");
        countries.put("Lebanon", 	"LB");
        countries.put("Lesotho", 	"LS");
        countries.put("Liberia", 	"LR");
        countries.put("Libya", 	"LY");
        countries.put("Liechtenstein", 	"LI");
        countries.put("Lithuania", 	"LT");
        countries.put("Luxembourg", 	"LU");
        countries.put("Macao", 	"MO");
        countries.put("Macedonia", 	"MK");
        countries.put("Madagascar", 	"MG");
        countries.put("Malawi", 	"MW");
        countries.put("Malaysia", 	"MY");
        countries.put("Maldives", 	"MV");
        countries.put("Mali", 	"ML");
        countries.put("Malta", 	"MT");
        countries.put("Marshall Islands", 	"MH");
        countries.put("Mauritania", 	"MR");
        countries.put("Mauritius", 	"MU");
        countries.put("Mayotte", 	"YT");
        countries.put("Mexico", 	"MX");
        countries.put("Micronesia", 	"FM");
        countries.put("Moldova", 	"MD");
        countries.put("Monaco", 	"MC");
        countries.put("Mongolia", 	"MN");
        countries.put("Montenegro", 	"ME");
        countries.put("Montserrat", 	"MS");
        countries.put("Morocco", 	"MA");
        countries.put("Mozambique", 	"MZ");
        countries.put("Myanmar", 	"MM");
        countries.put("Namibia", 	"NA");
        countries.put("Nauru", 	"NR");
        countries.put("Nepal", 	"NP");
        countries.put("Netherlands", 	"NL");
        countries.put("Netherlands Antilles", 	"AN");
        countries.put("New Caledonia", 	"NC");
        countries.put("New Zealand", 	"NZ");
        countries.put("Nicaragua", 	"NI");
        countries.put("Niger", 	"NE");
        countries.put("Nigeria", 	"NG");
        countries.put("Niue", 	"NU");
        countries.put("Norfolk Island", 	"NF");
        countries.put("Northern Mariana Islands", 	"MP");
        countries.put("Norway", 	"NO");
        countries.put("Oman", 	"OM");
        countries.put("Pakistan", 	"PK");
        countries.put("Palau", 	"PW");
        countries.put("Palestinian Territory) Occupied", 	"PS");
        countries.put("Panama", 	"PA");
        countries.put("Papua New Guinea", 	"PG");
        countries.put("Paraguay", 	"PY");
        countries.put("Peru", 	"PE");
        countries.put("Philippines", 	"PH");
        countries.put("Pitcairn", 	"PN");
        countries.put("Poland", 	"PL");
        countries.put("Portugal", 	"PT");
        countries.put("Puerto Rico", 	"PR");
        countries.put("Qatar", 	"QA");
        countries.put("Romania", 	"RO");
        countries.put("Russian Federation", 	"RU");
        countries.put("Rwanda", 	"RW");
        countries.put("Saint Barthelemy", 	"BL");
        countries.put("Saint Helena", 	"SH");
        countries.put("Saint Kitts And Nevis", 	"KN");
        countries.put("Saint Lucia", 	"LC");
        countries.put("Saint Martin", 	"MF");
        countries.put("Saint Pierre And Miquelon", 	"PM");
        countries.put("Saint Vincent And Grenadines", 	"VC");
        countries.put("Samoa", 	"WS");
        countries.put("San Marino", 	"SM");
        countries.put("Sao Tome And Principe", 	"ST");
        countries.put("Saudi Arabia", 	"SA");
        countries.put("Senegal", 	"SN");
        countries.put("Serbia", 	"RS");
        countries.put("Seychelles", 	"SC");
        countries.put("Sierra Leone", 	"SL");
        countries.put("Singapore", 	"SG");
        countries.put("Slovakia", 	"SK");
        countries.put("Slovenia", 	"SI");
        countries.put("Solomon Islands", 	"SB");
        countries.put("Somalia", 	"SO");
        countries.put("South Africa", 	"ZA");
        countries.put("Spain", 	"ES");
        countries.put("Sri Lanka", 	"LK");
        countries.put("Sudan", 	"SD");
        countries.put("Suriname", 	"SR");
        countries.put("Swaziland", 	"SZ");
        countries.put("Sweden", 	"SE");
        countries.put("Switzerland", 	"CH");
        countries.put("Syrian Arab Republic", 	"SY");
        countries.put("Taiwan", 	"TW");
        countries.put("Tajikistan", 	"TJ");
        countries.put("Tanzania", 	"TZ");
        countries.put("Thailand", 	"TH");
        countries.put("Timor-Leste", 	"TL");
        countries.put("Togo", 	"TG");
        countries.put("Tokelau", 	"TK");
        countries.put("Tonga", 	"TO");
        countries.put("Trinidad And Tobago", 	"TT");
        countries.put("Tunisia", 	"TN");
        countries.put("Turkey", 	"TR");
        countries.put("Turkmenistan", 	"TM");
        countries.put("Turks And Caicos Islands", 	"TC");
        countries.put("Tuvalu", 	"TV");
        countries.put("Uganda", 	"UG");
        countries.put("Ukraine", 	"UA");
        countries.put("United Arab Emirates", 	"AE");
        countries.put("United Kingdom", 	"GB");
        countries.put("United States", 	"US");
        countries.put("Uruguay", 	"UY");
        countries.put("Uzbekistan", 	"UZ");
        countries.put("Vanuatu", 	"VU");
        countries.put("Venezuela", 	"VE");
        countries.put("Viet Nam", 	"VN");
        countries.put("Wallis And Futuna", 	"WF");
        countries.put("Yemen", 	"YE");
        countries.put("Zambia", 	"ZM");
        countries.put("Zimbabwe",	"ZW");


        extensions = new HashMap<>();

        extensions.put("AF" , "93");
        extensions.put("AL" , "355");
        extensions.put("DZ" , "213");
        extensions.put("AS" , "1684 ");
        extensions.put("AD" , "376");
        extensions.put("AO" , "244");
        extensions.put("AI" , "1264");
        extensions.put("AQ" , "672");
        extensions.put("AG" , "1268");
        extensions.put("AR" , "54");
        extensions.put("AM" , "374");
        extensions.put("AW" , "297");
        extensions.put("AU" , "61");
        extensions.put("AT" , "43");
        extensions.put("AZ" , "994");
        extensions.put("BS" , "1242");
        extensions.put("BH" , "973");
        extensions.put("BD" , "880");
        extensions.put("BB" , "1246");
        extensions.put("BY" , "375");
        extensions.put("BE" , "32");
        extensions.put("BZ" , "501");
        extensions.put("BJ" , "229");
        extensions.put("BM" , "1441");
        extensions.put("BT" , "975");
        extensions.put("BO" , "591");
        extensions.put("BA" , "387");
        extensions.put("BW" , "267");
        extensions.put("BR" , "55");
        extensions.put("BN" , "673");
        extensions.put("BG" , "359");
        extensions.put("BF" , "226");
        extensions.put("BI" , "257");
        extensions.put("KH" , "855");
        extensions.put("CM" , "237");
        extensions.put("CA" , "1");
        extensions.put("CV" , "238");
        extensions.put("KY" , "1345");
        extensions.put("CF" , "236");
        extensions.put("TD" , "235");
        extensions.put("CL" , "56");
        extensions.put("CN" , "86");
        extensions.put("CX" , "61");
        extensions.put("CC" , "61");
        extensions.put("CO" , "57");
        extensions.put("KM" , "269");
        extensions.put("CK" , "682");
        extensions.put("CR" , "506");
        extensions.put("HR" , "385");
        extensions.put("CU" , "53");
        extensions.put("CY" , "357");
        extensions.put("CZ" , "420");
        extensions.put("DK" , "45");
        extensions.put("DJ" , "253");
        extensions.put("DM" , "1767");
        extensions.put("DO" , "1809");
        extensions.put("EC" , "593");
        extensions.put("EG" , "20");
        extensions.put("SV" , "503");
        extensions.put("GQ" , "240");
        extensions.put("ER" , "291");
        extensions.put("EE" , "372");
        extensions.put("ET" , "251");
        extensions.put("FK" , "500");
        extensions.put("FO" , "298");
        extensions.put("FJ" , "679");
        extensions.put("FI" , "358");
        extensions.put("FR" , "33");
        extensions.put("PF" , "689");
        extensions.put("GA" , "241");
        extensions.put("GM" , "220");
        extensions.put("GE" , "995");
        extensions.put("DE" , "49");
        extensions.put("GH" , "233");
        extensions.put("GI" , "350");
        extensions.put("GR" , "30");
        extensions.put("GL" , "299");
        extensions.put("GD" , "1473");
        extensions.put("GU" , "1671");
        extensions.put("GT" , "502");
        extensions.put("GN" , "224");
        extensions.put("GW" , "245");
        extensions.put("GY" , "592");
        extensions.put("HT" , "509");
        extensions.put("VA" , "39");
        extensions.put("HN" , "504");
        extensions.put("HK" , "852");
        extensions.put("HU" , "36");
        extensions.put("IS" , "354");
        extensions.put("IN" , "91");
        extensions.put("ID" , "62");
        extensions.put("IR" , "98");
        extensions.put("IQ" , "964");
        extensions.put("IE" , "353");
        extensions.put("IM" , "44");
        extensions.put("IL" , "972");
        extensions.put("IT" , "39");
        extensions.put("JM" , "1876");
        extensions.put("JP" , "81");
        extensions.put("JO" , "962");
        extensions.put("KZ" , "7");
        extensions.put("KE" , "254");
        extensions.put("KI" , "686");
        extensions.put("KR" , "82");
        extensions.put("KW" , "965");
        extensions.put("KG" , "996");
        extensions.put("LA" , "856");
        extensions.put("LV" , "371");
        extensions.put("LB" , "961");
        extensions.put("LS" , "266");
        extensions.put("LR" , "231");
        extensions.put("LY" , "218");
        extensions.put("LI" , "423");
        extensions.put("LT" , "370");
        extensions.put("LU" , "352");
        extensions.put("MO" , "853");
        extensions.put("MK" , "389");
        extensions.put("MG" , "261");
        extensions.put("MW" , "265");
        extensions.put("MY" , "60");
        extensions.put("MV" , "960");
        extensions.put("ML" , "223");
        extensions.put("MT" , "356");
        extensions.put("MH" , "692");
        extensions.put("MR" , "222");
        extensions.put("MU" , "230");
        extensions.put("YT" , "262");
        extensions.put("MX" , "52");
        extensions.put("FM" , "691");
        extensions.put("MD" , "373");
        extensions.put("MC" , "377");
        extensions.put("MN" , "976");
        extensions.put("ME" , "382");
        extensions.put("MS" , "1664");
        extensions.put("MA" , "212");
        extensions.put("MZ" , "258");
        extensions.put("MM" , "95");
        extensions.put("NA" , "264");
        extensions.put("NR" , "674");
        extensions.put("NP" , "977");
        extensions.put("NL" , "31");
        extensions.put("AN" , "599");
        extensions.put("NC" , "687");
        extensions.put("NZ" , "64");
        extensions.put("NI" , "505");
        extensions.put("NE" , "227");
        extensions.put("NG" , "234");
        extensions.put("NU" , "683");
        extensions.put("NF" , "672");
        extensions.put("MP" , "1670");
        extensions.put("NO" , "47");
        extensions.put("OM" , "968");
        extensions.put("PK" , "92");
        extensions.put("PW" , "680");
        extensions.put("PS" , "970");
        extensions.put("PA" , "507");
        extensions.put("PG" , "675");
        extensions.put("PY" , "595");
        extensions.put("PE" , "51");
        extensions.put("PH" , "63");
        extensions.put("PN" , "870");
        extensions.put("PL" , "48");
        extensions.put("PT" , "351");
        extensions.put("PR" , "1");
        extensions.put("QA" , "974");
        extensions.put("RO" , "40");
        extensions.put("RU" , "7");
        extensions.put("RW" , "250");
        extensions.put("BL" , "590");
        extensions.put("SH" , "290");
        extensions.put("KN" , "1869");
        extensions.put("LC" , "1758");
        extensions.put("MF" , "1599");
        extensions.put("PM" , "508");
        extensions.put("VC" , "1784");
        extensions.put("WS" , "685");
        extensions.put("SM" , "378");
        extensions.put("ST" , "239");
        extensions.put("SA" , "966");
        extensions.put("SN" , "221");
        extensions.put("RS" , "381");
        extensions.put("SC" , "248");
        extensions.put("SL" , "232");
        extensions.put("SG" , "65");
        extensions.put("SK" , "421");
        extensions.put("SI" , "386");
        extensions.put("SB" , "677");
        extensions.put("SO" , "252");
        extensions.put("ZA" , "27");
        extensions.put("ES" , "34");
        extensions.put("LK" , "94");
        extensions.put("SD" , "249");
        extensions.put("SR" , "597");
        extensions.put("SZ" , "268");
        extensions.put("SE" , "46");
        extensions.put("CH" , "41");
        extensions.put("SY" , "963");
        extensions.put("TW" , "886");
        extensions.put("TJ" , "992");
        extensions.put("TZ" , "255");
        extensions.put("TH" , "66");
        extensions.put("TL" , "670");
        extensions.put("TG" , "228");
        extensions.put("TK" , "690");
        extensions.put("TO" , "676");
        extensions.put("TT" , "1868");
        extensions.put("TN" , "216");
        extensions.put("TR" , "90");
        extensions.put("TM" , "993");
        extensions.put("TC" , "1649");
        extensions.put("TV" , "688");
        extensions.put("UG" , "256");
        extensions.put("UA" , "380");
        extensions.put("AE" , "971");
        extensions.put("GB" , "44");
        extensions.put("US" , "1");
        extensions.put("UY" , "598");
        extensions.put("UZ" , "998");
        extensions.put("VU" , "678");
        extensions.put("VE" , "58");
        extensions.put("VN" , "84");
        extensions.put("WF" , "681");
        extensions.put("YE" , "967");
        extensions.put("ZM" , "260");
        extensions.put("ZW" , "263");
    }

}
